global:
  scrape_interval: 5s
scrape_configs:

  - job_name: node_exporter
    static_configs:
      - targets:
          - node_exporter:9100

  - job_name: k6_exporter
    scrape_interval: 5s
    static_configs:
      - targets: ['k6_exporter:9091']

